services:
  gateway:
    build: .
    container_name: lamteknik-gateway
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./build/chains:/app/build/chains
      - ../backend/hyperledger-fabric/docker/explorer/organizations:/fabric/organizations:ro
    restart: unless-stopped
