services:
  gateway:
    build: .
    container_name: lamteknik-gateway
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./build/chains:/app/build/chains
    restart: unless-stopped
